Make zero downtime deploy with new unicorn config

diff --git a/config/templates/scripts/unicorn.sh.erb b/config/templates/scripts/unicorn.sh.erb
--- a/config/templates/scripts/unicorn.sh.erb
+++ b/config/templates/scripts/unicorn.sh.erb
@@ -18,7 +18,7 @@ APP_NAME=<%= fetch(:application) %>
 APP_ROOT=<%= fetch(:app_home_path) %>
 
 # environment settings
-CMD="<%= fetch(:bundle_exec) %> unicorn -c config/unicorn.rb -E <%= fetch(:rails_env) %> -D"
+CMD="<%= fetch(:bundle_exec) %> unicorn -c $APP_ROOT/current/config/unicorn.rb -E <%= fetch(:rails_env) %> -D"
 PID="$APP_ROOT/shared/pids/unicorn.pid"
 OLD_PID="$PID.oldbin"
 
@@ -53,6 +53,12 @@ case $1 in
   restart)
     sig QUIT && echo "Restarting $APP_NAME" && sleep 2 && su - $USER -c "$CMD" && exit 0
     echo >&2 "Couldn't reload, starting '$CMD' instead"
+    su - $USER -c "$CMD"
+    ;;
+
+  upgrade)
+    sig USR2 && echo reloaded OK && exit 0
+    echo >&2 "Couldn't upgrade, starting '$CMD' instead"
     su - $USER -c "$CMD"
     ;;
 
